// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuranSchool.Infrastructure.Data;

#nullable disable

namespace QuranSchool.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310235443_AddSaaSV3Modules")]
    partial class AddSaaSV3Modules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("QuranSchool.Domain.Entities.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsCurrent");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("StartDate");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.AdminProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Phone");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("AdminProfiles");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeOnly?>("CheckInTime");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Notes");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<Guid>("StudentId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CertificateNumber");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("ExamId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("IssuedDate");

                    b.Property<string>("PdfUrl");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("StudentId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.CmsPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlocksJson");

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Excerpt");

                    b.Property<string>("FeaturedImageUrl");

                    b.Property<string>("Icon");

                    b.Property<bool>("IsPublished");

                    b.Property<bool>("IsSystemPage");

                    b.Property<string>("MetaImage");

                    b.Property<string>("ParentSlug");

                    b.Property<Guid?>("SchoolId");

                    b.Property<string>("SeoDescription");

                    b.Property<string>("SeoTitle");

                    b.Property<bool>("ShowInMenu");

                    b.Property<string>("Slug")
                        .IsRequired();

                    b.Property<int>("SortOrder");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("CmsPages");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.DonationCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<decimal>("CurrentAmount");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished");

                    b.Property<Guid?>("SchoolId");

                    b.Property<decimal>("TargetAmount");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("DonationCampaigns");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.DonationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<Guid>("CampaignId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("DonorName")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<bool>("IsAnonymous");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Note");

                    b.Property<int>("PaymentType");

                    b.Property<Guid>("SchoolId");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("DonationRecords");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.DonorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("InternalNote");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRecurring");

                    b.Property<string>("Phone");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("DonorProfiles");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int?>("EndVerse");

                    b.Property<DateTime>("ExamDate");

                    b.Property<string>("ExamLevel");

                    b.Property<Guid>("ExaminerId");

                    b.Property<decimal>("FinalScore")
                        .HasPrecision(5, 2);

                    b.Property<string>("FinalStatus")
                        .IsRequired();

                    b.Property<string>("GlobalComment");

                    b.Property<Guid?>("GroupId");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsLevelProgressionExam");

                    b.Property<Guid>("SchoolId");

                    b.Property<int?>("StartVerse");

                    b.Property<Guid>("StudentId");

                    b.Property<Guid?>("SurahId");

                    b.Property<string>("TargetLevel");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ExaminerId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SurahId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.ExamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("ExamId");

                    b.Property<string>("Grade");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPassed");

                    b.Property<string>("Notes");

                    b.Property<Guid>("SchoolId");

                    b.Property<decimal>("Score");

                    b.Property<Guid>("StudentId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamResult");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.ExamVerseEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AssistanceGiven");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("ExamId");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("VerseId");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("VerseId");

                    b.ToTable("ExamVerseEvaluations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.ExamWordAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnnotationType")
                        .IsRequired();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("VerseEvaluationId");

                    b.Property<Guid>("WordId");

                    b.HasKey("Id");

                    b.HasIndex("VerseEvaluationId");

                    b.HasIndex("WordId");

                    b.ToTable("ExamWordAnnotations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Examiner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Phone");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Examiners");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.FinancialProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime?>("StartDate");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("FinancialProjects");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2);

                    b.Property<string>("AttachmentUrl");

                    b.Property<Guid>("CategoryId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<Guid?>("DonorId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Note");

                    b.Property<string>("PaymentMethod")
                        .IsRequired();

                    b.Property<Guid?>("ProjectId");

                    b.Property<string>("Reference");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DonorId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SchoolId");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid?>("LevelId");

                    b.Property<int>("MaxCapacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid?>("TeacherId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Homework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AttachmentUrl");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("DueDate");

                    b.Property<Guid?>("GroupId");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("TeacherId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Homeworks");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.HomeworkAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("Grade");

                    b.Property<Guid>("HomeworkId");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<Guid>("StudentId");

                    b.Property<string>("StudentNotes");

                    b.Property<DateTime?>("SubmittedAt");

                    b.Property<string>("TeacherFeedback");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("HomeworkId");

                    b.HasIndex("StudentId");

                    b.ToTable("HomeworkAssignments");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int?>("EndSurah");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Order");

                    b.Property<Guid>("SchoolId");

                    b.Property<int?>("StartSurah");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRead");

                    b.Property<Guid>("ReceiverId");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("SenderId");

                    b.Property<DateTime>("SentAt");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.MosqueSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<int>("CalculationMethod");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PrayersJson")
                        .IsRequired();

                    b.Property<Guid?>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("MosqueSettings");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRead");

                    b.Property<string>("ReferenceId");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Occupation");

                    b.Property<string>("Phone");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(10, 2);

                    b.Property<string>("DiscountReason");

                    b.Property<DateTime>("DueDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("PaidDate");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<Guid>("StudentId");

                    b.Property<string>("TransactionReference");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionType")
                        .IsRequired();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Module")
                        .IsRequired();

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("EndVerse");

                    b.Property<int?>("HizbNumber");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("JuzNumber");

                    b.Property<int?>("QualityScore");

                    b.Property<DateTime>("RecordDate");

                    b.Property<Guid>("SchoolId");

                    b.Property<int?>("StartVerse");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<Guid>("StudentId");

                    b.Property<string>("SurahName");

                    b.Property<int?>("SurahNumber");

                    b.Property<string>("TeacherNotes");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("ProgressRecords");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSystemRole");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("PermissionId");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("DayOfWeek")
                        .IsRequired();

                    b.Property<TimeOnly>("EndTime");

                    b.Property<Guid>("GroupId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Notes");

                    b.Property<string>("RoomName");

                    b.Property<Guid>("SchoolId");

                    b.Property<TimeOnly>("StartTime");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LogoUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Phone");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EndTime");

                    b.Property<int?>("EndVerse");

                    b.Property<Guid?>("GroupId");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsOnline");

                    b.Property<string>("MeetingUrl");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("SessionObjective");

                    b.Property<string>("StartTime");

                    b.Property<int?>("StartVerse");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<Guid?>("SurahId");

                    b.Property<Guid>("TeacherId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("SessionId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<Guid>("StudentId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("SessionAttendances");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionRecitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("EndVerse");

                    b.Property<string>("GlobalComment");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("QualityScore");

                    b.Property<int>("RecitationOrder");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("SessionId");

                    b.Property<int>("StartVerse");

                    b.Property<Guid>("StudentId");

                    b.Property<Guid>("SurahId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SurahId");

                    b.ToTable("SessionRecitations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionVerseEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AssistanceGiven");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("SessionRecitationId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("VerseId");

                    b.HasKey("Id");

                    b.HasIndex("SessionRecitationId");

                    b.HasIndex("VerseId");

                    b.ToTable("SessionVerseEvaluations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionWordAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnnotationType")
                        .IsRequired();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("SessionVerseEvaluationId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("WordId");

                    b.HasKey("Id");

                    b.HasIndex("SessionVerseEvaluationId");

                    b.HasIndex("WordId");

                    b.ToTable("SessionWordAnnotations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.StaffAbsence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsValidated");

                    b.Property<string>("Reason");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("UserId");

                    b.ToTable("StaffAbsences");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.StaffContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("DocumentUrl");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(18, 2);

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("UserId");

                    b.ToTable("StaffContracts");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Badges")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CurrentLevel");

                    b.Property<int>("CurrentStreak");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime>("EnrollmentDate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("GroupId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("LongestStreak");

                    b.Property<Guid?>("ParentId");

                    b.Property<string>("Phone");

                    b.Property<string>("PhotoUrl");

                    b.Property<Guid>("SchoolId");

                    b.Property<int>("TotalXP");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.StudentMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AudioUrl");

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CustomDescription");

                    b.Property<DateTime>("DueDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("QualityScore");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<Guid>("StudentId");

                    b.Property<int?>("TargetId");

                    b.Property<string>("TargetType")
                        .IsRequired();

                    b.Property<string>("TeacherFeedback");

                    b.Property<Guid?>("TeacherId");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("StudentMissions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.StudentProgressSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlockedCount");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<int>("ForgottenCount");

                    b.Property<bool>("IsDeleted");

                    b.Property<double>("PerformanceScore")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("SessionId");

                    b.Property<Guid>("StudentId");

                    b.Property<Guid>("SurahId");

                    b.Property<int>("TajwidErrorsCount");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("VersesCovered");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentProgressSnapshots");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Surah", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Number");

                    b.Property<string>("RevelationType")
                        .IsRequired();

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Surahs");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("HireDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Phone");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Specialization");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.TeacherAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeOnly?>("CheckInTime");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Notes");

                    b.Property<Guid>("SchoolId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<Guid>("TeacherId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAttendances");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.TransactionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Icon");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("SchoolId");

                    b.Property<int>("Type");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("TransactionCategories");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<Guid>("LinkedProfileId");

                    b.Property<string>("LinkedProfileType")
                        .IsRequired();

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("PreferredLanguage")
                        .IsRequired();

                    b.Property<string>("RefreshToken");

                    b.Property<DateTime?>("RefreshTokenExpiryTime");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.UserActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Metadata");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("Timestamp");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActionLogs");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Verse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("SchoolId");

                    b.Property<Guid>("SurahId");

                    b.Property<string>("TextArabic")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("VerseNumber");

                    b.Property<int>("WordsCount");

                    b.HasKey("Id");

                    b.HasIndex("SurahId");

                    b.ToTable("Verses");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.VerseWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("NormalizedText")
                        .IsRequired();

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("VerseId");

                    b.Property<int>("WordIndex");

                    b.Property<string>("WordText")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("VerseId");

                    b.ToTable("VerseWords");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.VolunteerMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CurrentVolunteers");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<int>("RequiredVolunteers");

                    b.Property<Guid?>("SchoolId");

                    b.Property<string>("SkillsRequired");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("VolunteerMissions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.VolunteerSignup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("MissionId");

                    b.Property<string>("Notes");

                    b.Property<Guid>("SchoolId");

                    b.Property<DateTime>("SignupDate");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId");

                    b.ToTable("VolunteerSignups");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.AcademicYear", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany("AcademicYears")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany("Certificates")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.CmsPage", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.DonationCampaign", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.DonationRecord", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.DonationCampaign", "Campaign")
                        .WithMany("Donations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.DonorProfile", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Exam", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.User", "Examiner")
                        .WithMany()
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Group", "Group")
                        .WithMany("Exams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Examiner");

                    b.Navigation("Group");

                    b.Navigation("Student");

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.ExamResult", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany("ExamResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.ExamVerseEvaluation", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Exam", "Exam")
                        .WithMany("VerseEvaluations")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Verse", "Verse")
                        .WithMany()
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.ExamWordAnnotation", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.ExamVerseEvaluation", "VerseEvaluation")
                        .WithMany("WordAnnotations")
                        .HasForeignKey("VerseEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.VerseWord", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerseEvaluation");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.FinancialProject", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.TransactionCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.DonorProfile", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuranSchool.Domain.Entities.FinancialProject", "Project")
                        .WithMany("Transactions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Donor");

                    b.Navigation("Project");

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Group", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Level", "Level")
                        .WithMany("Groups")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany("Groups")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Level");

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Homework", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuranSchool.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.HomeworkAssignment", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Homework", "Homework")
                        .WithMany("Assignments")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Message", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.MosqueSettings", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Notification", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Payment", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Progress", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Group", "Group")
                        .WithMany("Schedules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Session", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuranSchool.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionAttendance", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Session", "Session")
                        .WithMany("Attendances")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionRecitation", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Session", "Session")
                        .WithMany("Recitations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionVerseEvaluation", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.SessionRecitation", "Recitation")
                        .WithMany("VerseEvaluations")
                        .HasForeignKey("SessionRecitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Verse", "Verse")
                        .WithMany()
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recitation");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionWordAnnotation", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.SessionVerseEvaluation", "VerseEvaluation")
                        .WithMany("WordAnnotations")
                        .HasForeignKey("SessionVerseEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.VerseWord", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerseEvaluation");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.StaffAbsence", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.StaffContract", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Student", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuranSchool.Domain.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuranSchool.Domain.Entities.School", null)
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.StudentMission", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.StudentProgressSnapshot", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.TeacherAttendance", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Attendances")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.TransactionCategory", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.User", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.UserActionLog", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Verse", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Surah", "Surah")
                        .WithMany("Verses")
                        .HasForeignKey("SurahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.VerseWord", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.Verse", "Verse")
                        .WithMany("Words")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.VolunteerMission", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.VolunteerSignup", b =>
                {
                    b.HasOne("QuranSchool.Domain.Entities.VolunteerMission", "Mission")
                        .WithMany("Signups")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranSchool.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.DonationCampaign", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.DonorProfile", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Exam", b =>
                {
                    b.Navigation("VerseEvaluations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.ExamVerseEvaluation", b =>
                {
                    b.Navigation("WordAnnotations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.FinancialProject", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Group", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Schedules");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Homework", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Level", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.School", b =>
                {
                    b.Navigation("AcademicYears");

                    b.Navigation("Groups");

                    b.Navigation("Students");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Session", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Recitations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionRecitation", b =>
                {
                    b.Navigation("VerseEvaluations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.SessionVerseEvaluation", b =>
                {
                    b.Navigation("WordAnnotations");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Certificates");

                    b.Navigation("ExamResults");

                    b.Navigation("Payments");

                    b.Navigation("ProgressRecords");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Surah", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.TransactionCategory", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.Verse", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("QuranSchool.Domain.Entities.VolunteerMission", b =>
                {
                    b.Navigation("Signups");
                });
#pragma warning restore 612, 618
        }
    }
}
